const SWIPER_HEIGHT = 55;
const SWIPER_WIDTH = 365;

const PADDING = 8.5;

const SWIPEABLE_DIMENSIONS_WRT_HEIGHT = SWIPER_HEIGHT -  2 * PADDING;

const BUTTON_WIDTH  = 50;
const BUTTON_DIMENSIONS = SWIPER_HEIGHT -  2 * PADDING;

const SWIPEABLE_DIMENSIONS_WRT_WIDTH = SWIPER_WIDTH -  2 * PADDING;


const HORIZONTAL_SWIPE_RANGE = SWIPER_WIDTH -  2 * PADDING - BUTTON_DIMENSIONS ;
// console.log(HORIZONTAL_SWIPE_RANGE,'HSR')

const STYLES = {
  SWIPER_HEIGHT,
  PADDING,
  SWIPER_WIDTH,
  SWIPEABLE_DIMENSIONS_WRT_HEIGHT,
  SWIPEABLE_DIMENSIONS_WRT_WIDTH,
  HORIZONTAL_SWIPE_RANGE,
  BUTTON_DIMENSIONS
}


export default STYLES;